In [5]:
import numpy as np

def convolution(image, kernel):
    # Membuat variabel untuk menyimpan ukuran gambar dan kernel
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    
    # Membuat variabel untuk menyimpan output gambar
    output = np.zeros_like(image)
    
    # Melakukan zero-padding pada gambar
    padded_image = np.zeros((image_height + 2, image_width + 2))
    padded_image[1:-1, 1:-1] = image
    
    # Melakukan konvolusi pada gambar dengan kernel
    for i in range(image_height):
        for j in range(image_width):
            output[i, j] = np.sum(kernel * padded_image[i:i+kernel_height, j:j+kernel_width])
    
    return output

image = np.array([[2, 0, 0], [5, 0, 0], [1, 0, 7]])
kernel = np.array([[1, 1, 2], [0, 0, 2], [4, 1, 1]])
output = convolution(image, kernel)

print(output)

[[ 5 20  0]
 [ 3 13  7]
 [ 5 19  0]]
